<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <h1>Página inicial</h1>
    <h2>Se você está vendo esta página, é porque fiz tudo certo!</h2>
    <p>Acesse um dos links a seguir:</p>
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/todo">Lista de Tarefas</a></li>
        <li><a href="/publish">Editor de Texto</a></li>
    </ul>
</body>
</html>